import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFileSync(join(root, path), 'utf8')

test('first launch uses a versioned, skippable AI and KataGo onboarding flow', () => {
  const types = read('src/main/lib/types.ts')
  const store = read('src/main/lib/store.ts')
  const app = read('src/renderer/src/App.tsx')
  const onboarding = read('src/renderer/src/features/onboarding/FirstRunOnboarding.tsx')

  assert.match(types, /onboardingVersion: number/)
  assert.match(types, /llmSetupStatus: LlmSetupStatus/)
  assert.match(types, /'unconfigured' \| 'verified' \| 'skipped' \| 'needs-attention'/)
  assert.match(store, /onboardingVersion: 0/)
  assert.match(store, /systemLocale = app\.getLocale\(\)/)
  assert.match(store, /reviewLanguage: defaultReviewLanguage\(\)/)
  assert.match(onboarding, /FIRST_RUN_ONBOARDING_VERSION = 1/)
  assert.match(onboarding, /detectSystemUiLocale\(\)/)
  assert.match(onboarding, /document\.documentElement\.lang = locale/)
  assert.match(onboarding, /continueLater/)
  assert.match(onboarding, /unchangedVerifiedConfiguration/)
  assert.match(onboarding, /llmSetupStatus: status/)
  assert.match(onboarding, /!apiKey\.trim\(\) && !dashboard\.systemProfile\.hasLlmApiKey/)
  assert.match(onboarding, /onboardingVersion: FIRST_RUN_ONBOARDING_VERSION/)
  assert.match(onboarding, /SUPPORTED_UI_LOCALES\.map/)
  assert.match(app, /settings\.onboardingVersion < FIRST_RUN_ONBOARDING_VERSION/)
})

test('AI setup verifies text, vision, and agent tools while keeping manual model entry', () => {
  const provider = read('src/main/services/llm/openaiCompatibleProvider.ts')
  const teacher = read('src/main/services/teacherAgent.ts')
  const onboarding = read('src/renderer/src/features/onboarding/FirstRunOnboarding.tsx')
  const app = read('src/renderer/src/App.tsx')

  assert.match(provider, /textCapability/)
  assert.match(provider, /visionCapability/)
  assert.match(provider, /toolsCapability/)
  assert.match(provider, /readiness_check/)
  assert.match(teacher, /setSettings\(\{ llmSetupStatus: 'needs-attention', llmLastVerifiedAt: '' \}\)/)
  assert.match(onboarding, /testResult\.capabilities\.text/)
  assert.match(onboarding, /testResult\.capabilities\.vision/)
  assert.match(onboarding, /testResult\.capabilities\.tools/)
  assert.match(onboarding, /<input value=\{model\} list="first-run-models"/)
  assert.match(app, /setLlmModelRefreshMessage\(`\$\{t\('noModelReturned'\)\}/)
  assert.doesNotMatch(app, /if \(!models\.length\) \{\s*setSelectedLlmModel\(''\)/)
})

test('unconfigured AI actions open settings instead of invoking the teacher runtime', () => {
  const app = read('src/renderer/src/App.tsx')
  const i18n = read('src/renderer/src/i18n.ts')
  assert.match(app, /function ensureAiTeacherReady\(\): boolean/)
  assert.match(app, /llmSetupStatus === 'verified'/)
  assert.match(app, /setLlmTestMessage\(t\('llmSetupRequired'\)\)/)
  assert.match(app, /setSettingsOpen\(true\)/)
  assert.match(app, /if \(!ensureAiTeacherReady\(\)\) return/)
  assert.match(app, /messages\.length === 0 && !hasRunningTask && llmReady/)
  assert.match(app, /placeholder=\{llmReady \? undefined : t\('connectAiTeacher'\)\}/)
  assert.match(app, /llmReady \? t\('llmReady'\) : t\('llmMissing'\)/)
  assert.match(i18n, /appStatusReady:\s*'工作台就绪'/)
  assert.match(i18n, /winrateReady:\s*'胜率图待命'/)
})

test('automatic KataGo benchmark is cancellable, bounded, and preempted by analysis', () => {
  const types = read('src/main/lib/types.ts')
  const store = read('src/main/lib/store.ts')
  const benchmark = read('src/main/services/katagoBenchmark.ts')
  const scheduler = read('src/main/services/analysis/scheduler.ts')
  const app = read('src/renderer/src/App.tsx')

  assert.match(types, /KataGoBenchmarkTaskStatus/)
  assert.match(store, /katagoAutoBenchmarkEnabled: true/)
  assert.match(benchmark, /timeoutMs: request\.timeoutMs \?\? 30_000/)
  assert.match(benchmark, /BenchmarkCancelledError/)
  assert.match(benchmark, /setSettings\(next\)/)
  assert.match(scheduler, /cancelKataGoBenchmark\(\)/)
  assert.match(app, /cancelKataGoBenchmark/)
  assert.match(app, /katagoAutoBenchmarkEnabled/)
  assert.match(app, /graphBusy \|\| territoryBusy \|\| liveAnalysis\.running/)
  assert.match(app, /benchmarkManualCancelRef/)
  assert.match(app, /if \(!benchmarkManualCancelRef\.current\) autoBenchmarkAttemptRef\.current = ''/)
  assert.match(app, /onlyIfNeeded: automatic/)
  assert.match(app, /status: `已复用缓存[\s\S]{0,220}visitsPerSecond: 0/)
  assert.match(app, /liveAnalysis\.visitsPerSecond > 0/)
})

test('settings keep five user-facing pages and fold remote engines into advanced analysis settings', () => {
  const app = read('src/renderer/src/App.tsx')
  const i18n = read('src/renderer/src/i18n.ts')

  assert.match(app, /type SettingsPageId = 'general' \| 'ai' \| 'katago' \| 'voice' \| 'about'/)
  assert.doesNotMatch(app, /id: 'remote',[\s\S]{0,120}settingsPages/)
  assert.match(app, /settings-remote-advanced" hidden=\{activeSettingsPage !== 'katago'\}/)
  assert.match(app, /t\('settingsGeneralTitle'\)/)
  assert.match(app, /t\('settingsAiTitle'\)/)
  assert.match(app, /t\('settingsAnalysisTitle'\)/)
  assert.match(app, /t\('settingsVoiceTitle'\)/)
  assert.match(app, /t\('settingsAboutTitle'\)/)
  assert.match(i18n, /technicalDetails: 'Technical details'/)
  assert.match(app, /<UserFacingError message=\{error\} t=\{t\}/)
})

test('KataGo model downloads pause without deleting partial data and resume with HTTP Range', () => {
  const assets = read('src/main/services/katago/katagoAssets.ts')
  const main = read('src/main/index.ts')
  const preload = read('src/preload/index.ts')
  const settingsPanel = read('src/renderer/src/features/settings/KataGoAssetsPanel.tsx')

  assert.match(assets, /Range: `bytes=\$\{resumeAt\}-`/)
  assert.match(assets, /createWriteStream\(tmp, \{ flags: resumed \? 'a' : 'w' \}\)/)
  assert.match(assets, /KataGoAssetInstallPausedError/)
  assert.match(assets, /stage: 'paused'/)
  assert.doesNotMatch(assets, /await unlink\(tmp\)\.catch\(\(\) => undefined\)\s*\n\s*const response/)
  assert.match(main, /katago-assets:cancel-install/)
  assert.match(preload, /cancelKataGoAssetInstall/)
  assert.match(settingsPanel, /installProgress\?\.stage === 'paused'/)
})
