import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()

function read(relativePath) {
  return readFileSync(join(root, relativePath), 'utf8')
}

test('KataGo candidate ranking uses before-position choices and current-player loss', () => {
  const katago = read('src/main/services/katago.ts')
  const runtime = read('src/main/services/katagoRuntime.ts')
  assert.match(runtime, /reportAnalysisWinratesAs = SIDETOMOVE/)
  assert.match(katago, /function playerWinrate/)
  assert.match(katago, /function playerScoreLead/)
  assert.match(katago, /FORCED_ACTUAL_EVIDENCE_MIN_VISITS = 1200/)
  assert.match(katago, /QUICK_FORCED_ACTUAL_REFINE_MIN_VISITS = 80/)
  assert.match(katago, /function sideToMoveAt/)
  assert.match(katago, /function initialPlayerFromRecord/)
  assert.match(katago, /function analysisKomiForRecord/)
  assert.match(katago, /normalizeSgfKomiForAnalysis/)
  assert.match(katago, /function blackWinrateFromSideToMove/)
  assert.match(katago, /function blackScoreLeadFromSideToMove/)
  assert.match(katago, /function responseSideToMove/)
  assert.match(katago, /match LizzieYzy by storing it as black-positive/)
  assert.match(katago, /reportAnalysisWinratesAs: 'SIDETOMOVE'/)
  assert.match(katago, /initialPlayer: rootInitialPlayer/)
  assert.match(katago, /move\.pass \? 'pass' : move\.gtp/)
  assert.match(katago, /sideToMove === 'B' \? percent : 100 - percent/)
  assert.match(katago, /sideToMove === 'B' \? rawScoreLead : -rawScoreLead/)
  assert.match(katago, /function playedMoveValue/)
  assert.match(katago, /function forcePlayedMoveQuery/)
  assert.match(katago, /function forcedPlayedCandidate/)
  assert.match(katago, /function candidateEvidenceVisits/)
  assert.match(katago, /function preferStrongerActualCandidate/)
  assert.match(katago, /function forcedActualVisits/)
  assert.match(katago, /candidateEvidenceVisits\(forcedCandidate\) > candidateEvidenceVisits\(candidate\)/)
  assert.match(katago, /const actual = preferStrongerActualCandidate\(candidate, forcedCandidate\)/)
  assert.match(katago, /const preferred = preferStrongerActualCandidate\(currentCandidate, forcedCandidate\)/)
  assert.match(katago, /forcedActualVisits\(maxVisits, FORCED_ACTUAL_EVIDENCE_MIN_VISITS\)/)
  assert.match(katago, /allowMoves\?:/)
  assert.match(katago, /payload\.allowMoves = query\.allowMoves/)
  assert.match(katago, /root\(beforeResponse, beforeSideToMove\)/)
  assert.match(katago, /root\(afterResponse, afterSideToMove\)/)
  assert.match(katago, /candidates\(beforeResponse, beforeSideToMove\)/)
  assert.match(katago, /playedMoveValue\(currentMove, searchMoves, afterRoot, forcedActual\)/)
  assert.match(katago, /playedLoss\(currentMove, best, actual\)/)
  assert.match(katago, /playerWinrate\(best\.winrate, currentMove\.color\) - playerWinrate\(actual\.winrate, currentMove\.color\)/)
  assert.match(katago, /playerScoreLead\(best\.scoreLead, currentMove\.color\) - playerScoreLead\(actual\.scoreLead, currentMove\.color\)/)
  assert.doesNotMatch(katago, /Math\.abs\(after\.winrate - before\.winrate\)/)
  assert.doesNotMatch(katago, /Math\.abs\(after\.scoreLead - before\.scoreLead\)/)
})

test('Board overlays display candidate values from the side-to-move perspective', () => {
  const app = read('src/renderer/src/App.tsx')
  const geometry = read('src/renderer/src/features/board/boardGeometry.ts')
  const timelineInteraction = read('src/renderer/src/features/board/timelineInteraction.ts')
  const galleryMock = read('src/renderer/src/features/gallery/uiGalleryMock.ts')

  assert.match(app, /analysis\.before\.topMoves\.length > 0 \? analysis\.before\.topMoves : analysis\.after\.topMoves/)
  assert.match(app, /function boardDisplayCandidateMoves/)
  assert.match(app, /displayWinrateForColor\(candidate\.winrate, color\)/)
  assert.match(app, /displayScoreLeadForColor\(candidate\.scoreLead, color\)/)
  assert.match(app, /const currentAnalysis = useMemo/)
  assert.match(app, /analysis\?\.moveNumber === moveNumber/)
  assert.match(app, /<GoBoardV2[\s\S]*record=\{boardRecord\}[\s\S]*moveNumber=\{boardMoveNumber\}[\s\S]*analysis=\{boardAnalysis\}/)
  assert.match(app, /<GoBoard record=\{record\} moveNumber=\{moveNumber\} analysis=\{currentAnalysis\}/)

  assert.match(geometry, /Math\.max\(0, Math\.min\(100, value\)\) \/ 100/)
  assert.match(geometry, /return Math\.max\(0, Math\.min\(100, value\)\)/)
  assert.doesNotMatch(geometry, /value <= 1\.00001/)
  assert.doesNotMatch(geometry, /value <= 1 \? value \* 100/)
  assert.match(timelineInteraction, /clampNumber\(value, 0, 100\)/)
  assert.doesNotMatch(timelineInteraction, /value <= 1 \? value \* 100/)
  assert.match(galleryMock, /winrate: 56/)
  assert.doesNotMatch(galleryMock, /winrate: 0\.56/)
  assert.match(geometry, /function playerWinrateValue/)
  assert.match(geometry, /function playerScoreValue/)
  assert.match(geometry, /export function candidatePerspectiveColor/)
  assert.match(geometry, /const displayColor = candidatePerspectiveColor\(analysis\)/)
  assert.match(geometry, /const winrateValue = playerWinrateValue\(getCandidateWinrate\(candidate\), displayColor\)/)
  assert.match(geometry, /const scoreValue = playerScoreValue\(getCandidateScore\(candidate\), displayColor\)/)

  const board = read('src/renderer/src/features/board/GoBoardV2.tsx')
  assert.match(board, /candidate\.winrateValue/)
  assert.match(board, /candidate\.scoreValue/)
})

test('Teacher agent sends board-display winrates and unambiguous score summaries', () => {
  const agent = read('src/main/services/teacherAgent.ts')
  const evidence = read('src/main/services/teacher/teachingEvidence.ts')
  const scorePerspective = read('src/main/services/teacher/scorePerspective.ts')
  const main = read('src/main/index.ts')
  const types = read('src/main/lib/types.ts')

  assert.match(agent, /winratePerspective/)
  assert.match(agent, /primaryFields: 'board-display\/player perspective'/)
  assert.match(agent, /scoreSummary\.leader/)
  assert.match(agent, /scoreSummaryFromBlackLead/)
  assert.match(agent, /compactCandidateForColor/)
  assert.match(agent, /displayWinrateForColor\(candidate\.winrate, color\)/)
  assert.match(agent, /blackWinrate: roundMetric\(candidate\.winrate, 2\)/)
  assert.match(agent, /playedMove\.playerWinrate/)
  assert.match(agent, /For score winner\/margin, use scoreSummary\.text\/leader\/leadPoints/)

  assert.match(evidence, /perspectiveColor/)
  assert.match(evidence, /blackWinrate/)
  assert.match(evidence, /scoreSummaryFromBlackLead/)
  assert.match(evidence, /displayWinrateForColor\(move\.winrate, perspectiveColor\)/)
  assert.match(evidence, /analysis\.playedMove\.playerWinrate/)
  assert.match(scorePerspective, /signConvention: 'black-positive'/)
  assert.match(scorePerspective, /leader === 'B' \? '黑' : '白'/)

  assert.match(types, /export interface KataGoScoreSummary/)
  assert.match(types, /'teacher'/)
  assert.match(types, /group\?: KataGoAnalysisGroup/)
  assert.match(main, /const group = payload\.group \?\? \(payload\.runId \? 'teacher' : 'single'\)/)
  assert.match(main, /const group = payload\.group \?\? \(payload\.runId \? 'teacher' : 'live'\)/)
})

test('Timeline and issue list treat KataGo winrate loss as percentage points', () => {
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /function normalizeLossPercent/)
  assert.match(app, /return Math\.max\(0, Math\.abs\(value\)\)/)
  assert.doesNotMatch(app, /Math\.abs\(value\) <= 1 \? Math\.abs\(value\) \* 100/)

  const timeline = read('src/renderer/src/features/board/WinrateTimelineV2.tsx')
  assert.match(timeline, /playedMove'\), 'winrateLoss'/)
  assert.match(timeline, /return Math\.max\(0, Math\.abs\(raw\)\)/)
  assert.doesNotMatch(timeline, /Math\.abs\(raw\) <= 1 \? raw \* 100 : raw/)

  const board = read('src/renderer/src/features/board/GoBoardV2.tsx')
  assert.match(board, /played\.winrateLoss/)
  assert.doesNotMatch(board, /const loss = Math\.max\(0, played\.scoreLoss/)

  assert.match(app, /normalizeLossPercent\(item\.playedMove\?\.winrateLoss\)/)
  assert.doesNotMatch(app, /sortedEvaluations\.map\(\(item\) => Math\.max\(0, item\.playedMove\?\.scoreLoss/)
})

test('Quick winrate graph uses KaTrain-style fast visits and refines suspected mistakes', () => {
  const katago = read('src/main/services/katago.ts')
  assert.match(katago, /QUICK_ANALYSIS_FAST_VISITS = 24/)
  assert.match(katago, /QUICK_ANALYSIS_MAX_SWEEP_VISITS = 80/)
  assert.match(katago, /QUICK_ANALYSIS_REFINE_VISITS = 180/)
  assert.match(katago, /QUICK_ANALYSIS_WIDE_ROOT_NOISE = 0/)
  assert.match(katago, /Math\.min\(QUICK_ANALYSIS_MAX_SWEEP_VISITS, Math\.round\(maxVisits\)\)/)
  assert.match(katago, /overrideSettings/)
  assert.match(katago, /Build the visible winrate line first/)
  assert.match(katago, /only for suspected mistakes during the refine pass/)
  assert.match(katago, /resolvePartialAfterMs/)
  assert.doesNotMatch(katago, /resolvePartialAfterMs:\s*8_000/)
  assert.match(katago, /schedulePartialResolve/)
  assert.match(katago, /playedMoveValue\(currentMove, beforeTopMoves, after, forcedActual\)/)
  assert.doesNotMatch(katago, /!playedCandidate && !forcedActual\) \{\n\s+return null/)
  assert.match(katago, /quick-refine-before/)
  assert.match(katago, /quick-refine-actual/)
  assert.match(katago, /forcedActualVisits\(refineVisits, QUICK_FORCED_ACTUAL_REFINE_MIN_VISITS\)/)
  assert.match(katago, /refineTopN/)

  const agent = read('src/main/services/teacherAgent.ts')
  assert.match(agent, /analysisMode: 'fast-sweep-plus-key-move-refine'/)
  assert.match(agent, /const requestedVisits = numberInput\(input, 'maxVisits', 24, 1, 600\)/)
  assert.match(agent, /const sweepVisits = Math\.min\(80, Math\.max\(24, requestedVisits\)\)/)
  assert.match(agent, /const refineTopN = count > 1 \? 2 : 4/)
  assert.match(agent, /cancelKataGoAnalysis\(\{ group: 'quick' \}\)/)

  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /QUICK_GRAPH_FAST_VISITS = 24/)
  assert.match(app, /QUICK_GRAPH_REFINE_VISITS = 180/)
  assert.match(app, /quickGraphFastVisits/)
  assert.match(app, /refineVisits/)
  assert.doesNotMatch(app, /maxVisits: 12,/)

  const review = read('scripts/review_game.py')
  assert.match(review, /allowMoves/)
  assert.match(review, /best_wr_black if color == "B" else 100\.0 - best_wr_black/)
})

test('Workbench reuses cache for automatic analysis but manual analysis refreshes the current move', () => {
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /ANALYSIS_CACHE_PREFIX/)
  assert.match(app, /ANALYSIS_CACHE_SCHEMA_VERSION = 'v6-evidence-aware-issues'/)
  assert.match(app, /goagent\.analysisCache\.\$\{ANALYSIS_CACHE_SCHEMA_VERSION\}\./)
  assert.match(app, /function analysisQuality/)
  assert.match(app, /function preferAnalysis/)
  assert.match(app, /candidateBestVisits\(analysis\) \* 5/)
  assert.match(app, /type RememberEvaluationOptions = \{\s+force\?: boolean\s+\}/)
  assert.match(app, /function mergeEvaluations/)
  assert.match(app, /function hasCompleteEvaluationGraph/)
  assert.match(app, /if \(forceManualRefresh\) \{\s+await cancelKataGoWork\(\{ group: 'quick' \}\)\s+\}/)
  assert.match(app, /warmupEvaluationGraph\(gameId, defaultMoveNumber, retryAttempt \+ 1\)/)
  assert.match(app, /loadStoredEvaluations\(cacheKey\)/)
  assert.match(app, /persistStoredEvaluations\(cacheKey, cached\)/)
  assert.match(app, /cachedAnalysisForGameMove\(gameId, targetMove\)/)
  assert.match(app, /已复用缓存/)
  assert.match(app, /const forceManualRefresh = options\.manual !== false/)
  assert.match(app, /const canReuseStrongCache = !forceManualRefresh/)
  assert.match(app, /options\.force \? nextAnalysis : \(preferAnalysis/)
  assert.match(app, /rememberEvaluation\(nextAnalysis, \{ force: forceManualRefresh \}\)/)
  assert.match(app, /setAnalysis\(\(current\) => forceManualRefresh \? nextAnalysis : preferAnalysis\(current, nextAnalysis\)\)/)
  assert.match(app, /rememberEvaluation\(result\.analysis, \{ force: true \}\)/)
})
