import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (relativePath) => readFileSync(join(root, relativePath), 'utf8')

test('Phase 0 stores provider profiles while retaining the legacy API-key fields', () => {
  const types = read('src/main/lib/types.ts')
  const store = read('src/main/lib/store.ts')
  assert.match(types, /LlmProviderId = 'openai-compatible' \| 'codex-app-server'/)
  assert.match(types, /interface LlmConnectionProfile/)
  assert.match(types, /activeLlmConnectionId: string/)
  assert.match(types, /llmConnections: LlmConnectionProfile\[\]/)
  assert.match(store, /LEGACY_LLM_CONNECTION_ID = 'openai-compatible-default'/)
  assert.match(store, /CHATGPT_LLM_CONNECTION_ID = 'chatgpt-codex'/)
  assert.match(store, /normalizeLlmConnections/)
  assert.match(store, /DEFAULT_OPENAI_MODEL = 'gpt-5\.6-sol'/)
  assert.match(store, /llmConnectionSchemaVersion: 2/)
  assert.match(store, /llmModel: active\?\.model \?\? persisted\.llmModel/)
  assert.match(store, /llmApiKeys\?: Record<string, SecretValue>/)
  assert.match(store, /saveLlmApiKeyForConnection/)
  assert.match(store, /getLlmApiKey/)
})

test('Phase 1 uses Codex App Server managed ChatGPT login, model discovery, streaming, and image input', () => {
  const client = read('src/main/services/llm/codexAppServerClient.ts')
  assert.match(client, /\['app-server', '--listen', 'stdio:\/\/'\]/)
  assert.match(client, /@openai\/codex-win32-x64/)
  assert.match(client, /app\.asar\.unpacked/)
  assert.match(client, /resolveCodexExecutable/)
  assert.match(client, /Windows PATH 指向了受保护的 Microsoft Store 应用文件/)
  assert.match(client, /request\('initialize'/)
  assert.match(client, /notify\('initialized'/)
  assert.match(client, /account\/read/)
  assert.match(client, /account\/login\/start/)
  assert.match(client, /useHostedLoginSuccessPage: true/)
  assert.match(client, /account\/logout/)
  assert.match(client, /model\/list/)
  assert.match(client, /includeHidden: true/)
  assert.match(client, /inputModalities/)
  assert.match(client, /stdin\.destroyed/)
  assert.match(client, /child\.stdin\.on\('error'/)
  assert.match(client, /class CodexTransportError/)
  assert.match(client, /private async requestWithRestart/)
  assert.match(client, /this\.events\.emit\('transport-failure'/)
  assert.match(client, /waitForTurnCompletion/)
  assert.match(client, /if \(this\.child !== child\) return/)
  assert.match(client, /handleProcessFailure/)
  assert.match(client, /type: 'localImage'/)
  assert.match(client, /sandboxPolicy: \{ type: 'readOnly' \}/)
  assert.doesNotMatch(client, /readOnly', access:/)
  assert.match(client, /item\/agentMessage\/delta/)
  assert.match(client, /turn\/completed/)
  assert.match(client, /turn\/interrupt/)
  assert.match(client, /request\('thread\/delete'/)
  assert.doesNotMatch(client, /apiKey:\s*profile/)
})

test('ChatGPT credentials are checked before OAuth and model defaults come from provider discovery', () => {
  const registry = read('src/main/services/llm/providerRegistry.ts')
  const onboarding = read('src/renderer/src/features/onboarding/FirstRunOnboarding.tsx')
  const packageJson = JSON.parse(read('package.json'))
  assert.match(registry, /connectionState\(profile\.id\)/)
  assert.match(registry, /if \(state\.ready\)/)
  assert.match(registry, /visionModels\.find\(\(model\) => model\.isDefault\)/)
  assert.match(registry, /recommendedModel: selected\?\.id/)
  assert.match(onboarding, /result\.recommendedModel \|\| result\.models\[0\]/)
  assert.match(onboarding, /已复用 Codex 的 ChatGPT 登录/)
  assert.equal(packageJson.dependencies['@openai/codex'], '0.148.0-alpha.20')
  assert.deepEqual(packageJson.build.asarUnpack, ['node_modules/@openai/codex-*/vendor/**/*'])
})

test('The teacher gathers KataGo evidence locally and sends final explanation through the active provider', () => {
  const registry = read('src/main/services/llm/providerRegistry.ts')
  const teacher = read('src/main/services/teacherAgent.ts')
  assert.match(registry, /runProviderTurn/)
  assert.match(registry, /profile\.provider === 'codex-app-server'/)
  assert.match(registry, /streamOpenAICompatibleToolTurn/)
  assert.match(teacher, /prefetchEvidenceForManagedProvider/)
  assert.match(teacher, /katago_analyzePosition/)
  assert.match(teacher, /katago_analyzeGameBatch/)
  assert.match(teacher, /board_captureTeachingImage/)
  assert.match(teacher, /runProviderTurn\(settings, messages/)
})

test('ChatGPT login is exposed without exposing tokens and the Python review entry is gone', () => {
  const main = read('src/main/index.ts')
  const preload = read('src/preload/index.ts')
  const globalTypes = read('src/renderer/src/global.d.ts')
  const app = read('src/renderer/src/App.tsx')
  assert.match(main, /llm:chatgpt-login/)
  assert.match(main, /shell\.openExternal\(url\)/)
  assert.match(preload, /startChatGptLogin/)
  assert.match(preload, /logoutChatGpt/)
  assert.match(globalTypes, /startChatGptLogin/)
  assert.match(app, /ChatGPT 登录/)
  assert.match(app, /systemProfile\.llmConnection\.ready/)
  const loginBridge = preload.match(/startChatGptLogin:[\s\S]*?logoutChatGpt:[^\n]+/)?.[0] ?? ''
  assert.doesNotMatch(loginBridge, /accessToken|refreshToken/)
  assert.equal(existsSync(join(root, 'scripts/review_game.py')), false)
  assert.equal(existsSync(join(root, 'src/main/services/review.ts')), false)
  assert.doesNotMatch(main, /review:start/)
})
