import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFileSync(join(root, path), 'utf8')

test('teacher persona settings include level, age, style, and evidence boundary', () => {
  const types = read('src/main/lib/types.ts')
  const store = read('src/main/lib/store.ts')
  const persona = read('src/main/services/teacher/teacherPersona.ts')
  const agent = read('src/main/services/teacherAgent.ts')
  assert.match(types, /defaultCoachLevel: CoachUserLevel/)
  assert.match(types, /defaultStudentRank: StudentRank/)
  assert.match(types, /defaultStudentAge: number/)
  assert.match(types, /defaultStudentAgeRange: StudentAgeRange/)
  assert.match(types, /teacherStyle: TeacherPersonaStyle/)
  assert.match(types, /teacherTerminologyDensity: TeacherTerminologyDensity/)
  assert.match(types, /teacherExplanationPace: TeacherExplanationPace/)
  assert.match(types, /teacherVariationDetail: TeacherVariationDetail/)
  assert.match(types, /export type StudentRank = 'sub1d' \| '1d' \| '2d' \| '3d' \| '4d' \| '5d' \| '6d' \| '7d' \| '8d' \| '9d'/)
  assert.match(types, /ageRange\?: StudentAgeRange/)
  assert.match(store, /defaultCoachLevel: 'intermediate'/)
  assert.match(store, /defaultStudentRank: 'sub1d'/)
  assert.match(store, /defaultStudentAge: 0/)
  assert.match(store, /defaultStudentAgeRange: 'unknown'/)
  assert.match(store, /teacherStyle: 'balanced'/)
  assert.match(store, /teacherTerminologyDensity: 'medium'/)
  assert.match(store, /teacherExplanationPace: 'standard'/)
  assert.match(store, /teacherVariationDetail: 'moderate'/)
  assert.match(persona, /rank\?: StudentRank/)
  assert.match(persona, /学生段位：1段以下/)
  assert.match(persona, /学生段位：9段/)
  assert.match(persona, /value === '10k' \|\| value === '1k'/)
  assert.match(persona, /exactAge\?: number/)
  assert.match(persona, /风格和年龄只影响表达方式/)
  assert.match(persona, /不能改变 KataGo/)
  assert.match(agent, /normalizeStudentRank/)
  assert.match(agent, /normalizeExactStudentAge/)
  assert.match(agent, /buildTeacherPersonaInstruction/)
})

test('teacher sessions are typed, persisted through IPC, and exposed in composer', () => {
  const types = read('src/main/lib/types.ts')
  const service = read('src/main/services/teacherSession.ts')
  const preload = read('src/preload/index.ts')
  const main = read('src/main/index.ts')
  const composer = read('src/renderer/src/features/teacher/TeacherComposerPro.tsx')
  const app = read('src/renderer/src/App.tsx')
  assert.match(types, /interface TeacherSession/)
  assert.match(service, /electron-store/)
  assert.match(service, /archiveTeacherSession/)
  assert.match(service, /deleteTeacherSession/)
  assert.match(service, /hasVisibleTeacherMessages/)
  assert.match(service, /\.filter\(hasVisibleTeacherMessages\)/)
  assert.match(preload, /listTeacherSessions/)
  assert.match(preload, /deleteTeacherSession/)
  assert.match(main, /teacher-sessions:update-messages/)
  assert.match(main, /teacher-sessions:delete/)
  assert.match(composer, /Ask GoMentor/)
  assert.match(composer, /onKeyDown=\{handleTextareaKeyDown\}/)
  assert.match(composer, /requestSubmit/)
  assert.match(app, /新会话/)
  assert.match(app, /历史会话/)
  assert.match(app, /deleteTeacherSessionById/)
  assert.match(app, /onDeleteTeacherSession/)
  assert.match(app, /submitTeacherPromptText/)
  assert.match(app, /onQuickPrompt/)
  assert.match(app, /onPersonaSettingsSaved/)
  assert.match(app, /保存失败/)
  assert.match(app, /hasVisibleTeacherSessionContent/)
  assert.match(app, /teacherSessionPreview/)
  assert.doesNotMatch(app, /aria-label="归档当前会话"/)
  assert.match(app, /gomentor:teacher-session-action/)
})
