import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFileSync(join(root, path), 'utf8')

test('KataGo root ownership is preserved for positional judgement', () => {
  const types = read('src/main/lib/types.ts')
  const katago = read('src/main/services/katago.ts')

  assert.match(types, /ownership\?: number\[\]/)
  assert.match(types, /ownershipStdev\?: number\[\]/)
  assert.match(katago, /rootInfo\?: \{/)
  assert.match(katago, /rootInfo\.ownership/)
  assert.match(katago, /rootInfo\.ownershipStdev/)
  assert.match(katago, /ownership: Array\.isArray\(response\.rootInfo\.ownership\)/)
})

test('renderer has a reusable territory judgement model and premium board overlay', () => {
  const model = read('src/renderer/src/features/board/territoryJudgement.ts')
  const board = read('src/renderer/src/features/board/GoBoardV2.tsx')
  const css = read('src/renderer/src/features/board/board-v2.css')

  assert.match(model, /export function buildTerritoryJudgement/)
  assert.match(model, /function calibratedOwnershipSign/)
  assert.match(model, /OWNERSHIP_STONE_CALIBRATION_THRESHOLD/)
  assert.match(model, /TerritoryDisplayMode = 'heat' \| 'blocks' \| 'marks'/)
  assert.match(model, /source: 'root'/)
  assert.match(model, /best-continuation/)
  assert.match(board, /territoryJudgement\?: TerritoryJudgement/)
  assert.match(board, /function TerritoryOverlay/)
  assert.match(board, /function territoryStrandedStones/)
  assert.match(board, /function TerritoryStrandedStoneMark/)
  assert.match(board, /candidates\.length > Math\.max\(8, stones\.length \* 0\.32\)/)
  assert.match(board, /transform="rotate\(45\)"/)
  assert.doesNotMatch(board, /rotate\(45 \$\{15\} \$\{-22\}\)/)
  assert.match(board, /ks-territory-layer/)
  assert.match(board, /ks-territory-stranded-stones-layer/)
  assert.match(board, /ks-territory-stranded-stone--in-/)
  assert.match(board, /ks-territory-dot--/)
  assert.match(board, /visualOwner = isUnclear \? 'unclear' : cellInfo\.owner/)
  assert.match(css, /\.ks-territory-layer--heat/)
  assert.match(css, /\.ks-territory-stranded-stones-layer/)
  assert.match(css, /\.ks-territory-stranded-stone--in-B/)
  assert.match(css, /\.ks-territory-stranded-stone--in-W/)
  assert.match(css, /\.ks-territory-stranded-stone__chip/)
  assert.doesNotMatch(css, /ks-territory-stranded-stone__ring/)
  assert.doesNotMatch(css, /ks-territory-stranded-stone__halo/)
  assert.match(css, /\.ks-territory-layer--blocks/)
  assert.match(css, /\.ks-territory-layer--marks/)
  assert.match(css, /\.ks-territory-dot--B/)
  assert.match(css, /\.ks-territory-dot--W/)
  assert.match(css, /\.ks-territory-dot--unclear/)
})

test('workbench exposes positional judgement controls and summary without replacing analysis flow', () => {
  const app = read('src/renderer/src/App.tsx')
  const panel = read('src/renderer/src/features/board/TerritoryJudgementPanel.tsx')
  const styles = read('src/renderer/src/styles.css')
  const i18n = read('src/renderer/src/i18n.ts')

  assert.match(app, /const \[territoryEnabled, setTerritoryEnabled\]/)
  assert.match(app, /buildTerritoryJudgement\(boardAnalysis/)
  assert.match(app, /runTerritoryJudgementAnalysis/)
  assert.match(app, /function toggleTerritoryJudgement/)
  assert.match(app, /!territoryJudgement\.available/)
  assert.match(app, /void runTerritoryJudgementAnalysis\(\)/)
  assert.match(app, /territoryControl=\{\(/)
  const boardTableStart = app.indexOf('<div className="board-table board-table--v2">')
  const boardComponentStart = app.indexOf('{boardRecord && boardRecord.boardSize >= 2', boardTableStart)
  assert.ok(boardTableStart >= 0 && boardComponentStart > boardTableStart)
  assert.doesNotMatch(app.slice(boardTableStart, boardComponentStart), /<TerritoryControlPanel/)
  assert.match(app, /territoryJudgement=\{territoryEnabled \? territoryJudgement : null\}/)
  assert.match(app, /<TerritorySummaryStrip judgement=\{territoryJudgement\}/)
  assert.doesNotMatch(panel, /territory-control__segments/)
  assert.doesNotMatch(panel, /onModeChange/)
  assert.doesNotMatch(panel, /onDeepen/)
  assert.doesNotMatch(panel, /territory-control__deepen/)
  assert.match(panel, /territoryBlackStrong/)
  assert.match(panel, /territory-control__legend/)
  assert.match(panel, /territoryBlackTerritory/)
  assert.match(panel, /territoryWhiteTerritory/)
  assert.match(panel, /territoryContested/)
  assert.match(styles, /\.territory-control/)
  assert.match(styles, /\.territory-control--compact/)
  assert.doesNotMatch(styles, /territory-control__segments/)
  assert.doesNotMatch(styles, /territory-control__deepen/)
  assert.match(styles, /\.territory-control__legend-dot--black/)
  assert.doesNotMatch(styles.match(/\.territory-control\s*\{[\s\S]*?\}/)?.[0] ?? '', /position:\s*absolute/)
  assert.match(styles, /\.territory-summary/)
  assert.match(i18n, /territoryJudgement: '形势判断'/)
  assert.match(i18n, /territoryBlackTerritory: '黑地'/)
  assert.doesNotMatch(i18n, /territoryDeepen/)
})

test('UI gallery includes positional judgement sample data for visual QA', () => {
  const gallery = read('src/renderer/src/features/gallery/UiGallery.tsx')
  const mock = read('src/renderer/src/features/gallery/uiGalleryMock.ts')

  assert.match(mock, /function mockOwnership/)
  assert.match(mock, /ownership: mockOwnership\(19\)/)
  assert.match(gallery, /renderStones\(galleryRecord, moveNumber\)/)
  assert.match(gallery, /TerritoryControlPanel/)
  assert.match(gallery, /TerritorySummaryStrip/)
  assert.match(gallery, /buildTerritoryJudgement\(galleryAnalysis/)
})
