import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (path) => readFileSync(join(root, path), 'utf8')

test('TTS provider policy uses explicit selected provider only', () => {
  const types = read('src/main/lib/types.ts')
  const registry = read('src/main/services/tts/index.ts')
  const providerTypes = read('src/main/services/tts/ttsTypes.ts')
  assert.match(types, /kokoro-bundled/)
  assert.match(types, /custom-openai-compatible/)
  assert.match(types, /custom-http-json/)
  assert.match(types, /external-local-service/)
  assert.doesNotMatch(types, /system-web-speech|speechSynthesis/)
  assert.match(providerTypes, /assertSelectedProvider/)
  assert.match(registry, /selectedProvider\(settings\)/)
  assert.doesNotMatch(registry, /tryNextProvider|providerChain|autoSwitchProvider/)
})

test('Kokoro bundled assets and scripts are wired', () => {
  const packageJson = JSON.parse(read('package.json'))
  assert.equal(packageJson.scripts['prepare:tts-assets'], 'node scripts/prepare_tts_assets.mjs')
  assert.equal(packageJson.scripts['check:tts-assets'], 'node scripts/check_tts_assets.mjs')
  assert.equal(packageJson.scripts['smoke:tts'], 'node scripts/smoke_tts.mjs')
  assert.match(packageJson.scripts['check:release-quality'], /check:tts-assets/)
  assert.match(packageJson.scripts['check:release-quality'], /smoke:tts/)
  const manifest = JSON.parse(read('data/tts/kokoro/zh-CN/manifest.json'))
  assert.equal(manifest.provider, 'kokoro-bundled')
  assert.equal(manifest.language, 'zh-CN')
  assert.equal(manifest.license, 'Apache-2.0')
  assert.match(manifest.modelFile, /model_int8\.onnx/)
  assert.match(manifest.runtimeModelFile, /model_quantized\.onnx/)
})

test('Kokoro zh-CN synthesis does not route Chinese text through the English phonemizer', () => {
  const provider = read('src/main/services/tts/kokoroBundledProvider.ts')
  const workerClient = read('src/main/services/tts/kokoroWorkerClient.ts')
  const workerScript = read('scripts/tts_kokoro_worker.mjs')
  const g2p = read('src/main/services/tts/misakiZhG2p.ts')
  const runtime = read('src/main/services/tts/ttsPythonRuntime.ts')
  const requirements = read('scripts/requirements-tts.txt')
  const g2pScript = read('scripts/tts_misaki_zh_g2p.py')
  const speechText = read('src/main/services/tts/speechText.ts')
  const service = read('src/main/services/tts/index.ts')
  const controls = read('src/renderer/src/features/tts/TeacherSpeechControls.tsx')
  const smoke = read('scripts/smoke_tts.mjs')
  assert.match(provider, /phonemizeChineseWithMisaki/)
  assert.match(provider, /synthesizeKokoroChunkInWorker/)
  assert.match(provider, /splitSpeechIntoChunks/)
  assert.match(provider, /concatPcm16WavFiles/)
  assert.doesNotMatch(provider, /tts\.generate\(text/)
  assert.doesNotMatch(provider, /generate_from_ids/)
  assert.match(workerClient, /tts_kokoro_worker\.mjs/)
  assert.match(workerClient, /ELECTRON_RUN_AS_NODE/)
  assert.match(workerClient, /materializeTtsScript/)
  assert.match(workerClient, /pending/)
  assert.match(workerScript, /languageCode/)
  assert.match(workerScript, /KokoroTTS\.from_pretrained/)
  assert.match(workerScript, /generate_from_ids/)
  assert.match(workerScript, /localVoiceFiles/)
  assert.match(workerScript, /process\.stdin/)
  assert.match(workerScript, /process\.stdout/)
  assert.match(g2p, /tts_misaki_zh_g2p\.py/)
  assert.match(runtime, /Python 3\.10-3\.13/)
  assert.match(requirements, /misaki\[zh\]/)
  assert.match(g2pScript, /ZHG2P\(version="1\.1"\)/)
  assert.match(g2pScript, /latin_token_to_speech/)
  assert.match(provider, /prepareWavForBrowserPlayback/)
  assert.match(provider, /assertSpeechLanguageMatches/)
  assert.match(workerScript, /return 'z'/)
  assert.doesNotMatch(workerScript, /voiceIds\.has\(voice\)\) return 'a'/)
  assert.match(speechText, /detectSpeechLanguage/)
  assert.match(speechText, /TTS 语言不匹配/)
  assert.match(speechText, /COORDINATE_LETTER_SPEECH/)
  assert.match(speechText, /latinTokenToSpeech/)
  assert.match(speechText, /numberToChinese/)
  assert.doesNotMatch(speechText, /坐标\$\{letterName\}/)
  assert.doesNotMatch(g2pScript, /坐标\{letter_name\}/)
  assert.match(service, /payload\.readMode/)
  assert.match(service, /limitSpeechLength/)
  assert.match(controls, /speechSourceText/)
  assert.match(controls, /splitProgressiveSpeech/)
  assert.match(controls, /playProgressiveChunks/)
  assert.match(controls, /prefetchChunk/)
  assert.match(controls, /synthLockRef/)
  assert.match(controls, /runIdRef/)
  assert.match(controls, /playbackDoneRef/)
  assert.doesNotMatch(controls, /structuredResult\?\.summary/)
  assert.doesNotMatch(controls, /readMode: 'summary'/)
  assert.match(smoke, /runKokoroWorkerSmoke/)
  assert.match(smoke, /tts_kokoro_worker\.mjs/)
  assert.match(smoke, /Misaki zh G2P/)
  assert.match(smoke, /invalid float sample/)
  assert.doesNotMatch(smoke, /return 'a'/)
})

test('custom TTS API is explicit and stored separately from public settings', () => {
  const store = read('src/main/lib/store.ts')
  const preload = read('src/preload/index.ts')
  assert.match(store, /ttsCustomApiKey/)
  assert.match(store, /getTtsCustomApiKey/)
  assert.match(preload, /synthesizeTts/)
  assert.match(preload, /getSavedTtsApiKey/)
})
