import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { test } from 'node:test'

const repoRoot = new URL('..', import.meta.url)

async function text(path) {
  return readFile(new URL(path, repoRoot), 'utf8')
}

test('Zhizi cloud engine is wired as a first-class KataGo engine mode', async () => {
  assert.equal(existsSync(new URL('src/main/services/zhiziGtpEngine.ts', repoRoot)), true)
  const types = await text('src/main/lib/types.ts')
  const store = await text('src/main/lib/store.ts')
  const katago = await text('src/main/services/katago.ts')
  const diagnostics = await text('src/main/services/diagnostics/index.ts')
  const systemProfile = await text('src/main/services/systemProfile.ts')
  const packageJson = await text('package.json')

  assert.match(types, /KataGoEngineMode = 'auto' \| 'persistent' \| 'spawn' \| 'ikatago' \| 'zhizi'/)
  assert.match(types, /zhiziClientBin: string/)
  assert.match(types, /zhiziGpuType: string/)
  assert.match(types, /zhiziUseWhenLocalSlow: boolean/)
  assert.match(store, /zhiziGpuType: 'vip-share'/)
  assert.match(store, /zhiziToken\?: SecretValue/)
  assert.match(packageJson, /socket\.io-client/)
  assert.match(katago, /queryZhiziGtpAnalysisBatch/)
  assert.match(katago, /shouldPreferZhiziGtpEngine\(settings, runtime\.ready\)/)
  assert.match(katago, /settings\.katagoEngineMode === 'zhizi'/)
  assert.match(katago, /Local KataGo analysis failed in opt-in slow-machine mode; falling back to Zhizi cloud/)
  assert.match(katago, /settings\.zhiziUseWhenLocalSlow/)
  assert.match(katago, /zhiziGtpConfigured\(settings\)/)
  assert.match(diagnostics, /使用智子云远程算力/)
  assert.match(systemProfile, /Zhizi Cloud Direct Ready/)
})

test('Zhizi cloud engine uses real GTP kata-analyze output instead of iKataGo analysis JSON', async () => {
  const engine = await text('src/main/services/zhiziGtpEngine.ts')
  const protocol = await text('src/main/services/zhiziGtpProtocol.ts')
  const session = await text('src/main/services/zhiziSocketSession.ts')
  const probe = await text('src/main/services/zhiziConnectionProbe.ts')
  const renderer = await text('src/renderer/src/App.tsx')
  const preload = await text('src/preload/index.ts')
  const main = await text('src/main/index.ts')
  const store = await text('src/main/lib/store.ts')
  const i18n = await text('src/renderer/src/i18n.ts')
  const docs = await text('docs/ZHIZI_CLOUD_ENGINE.md')
  const auth = await text('src/main/services/zhiziCloudAuth.ts')

  assert.match(engine, /kata-analyze \$\{player\} 25 rootInfo true maxmoves 20/)
  assert.match(engine, /parseKataAnalyzeInfo/)
  assert.match(engine, /zhiziResponseVisitTotal/)
  assert.match(engine, /zhiziAnalysisReachedVisits/)
  assert.match(engine, /emitAnalyzeProgress/)
  assert.match(engine, /onSearchProgress/)
  assert.match(engine, /emitAnalyzeProgress\(request, query\.id, player, output, progressState, true\)/)
  assert.match(engine, /hasGtpTerminator/)
  assert.match(engine, /countGtpResponses/)
  assert.match(engine, /sendCommands\(channel, setupCommands, '智子云 GTP 初始化局面'\)/)
  assert.match(engine, /kata-set-rules chinese/)
  assert.match(engine, /time_settings 0 5 1/)
  assert.doesNotMatch(engine, /await sendCommand\(`play \$\{color\}/)
  assert.match(engine, /\\r\?\\n\\r\?\\n/)
  assert.match(protocol, /completeLines\[completeLines\.length - 1\]/)
  assert.match(session, /GTP ready\|beginning main protocol loop/)
  assert.match(session, /socket\.on\('ready'/)
  assert.match(session, /reconnection: true/)
  assert.match(session, /reconnectionDelayMax: 8_000/)
  assert.match(session, /READY_FALLBACK_MS = 4_000/)
  assert.match(session, /MAX_START_ATTEMPTS = 3/)
  assert.match(engine, /settings\.zhiziToken\.trim\(\)/)
  assert.match(engine, /settings\.katagoEngineMode === 'zhizi' && Boolean\(settings\.zhiziClientBin\.trim\(\)\)/)
  assert.match(engine, /智子云未登录：请先在设置里用账号密码或短信验证码登录智子云/)
  assert.match(engine, /不需要填写 zz-ikatago 路径/)
  assert.match(engine, /智子云旧连接器未配置完整/)
  assert.match(session, /fetch-socketio-token/)
  assert.match(session, /not_enough_credit/)
  assert.match(session, /VIP 共享引擎/)
  assert.match(session, /socket\.emit\('stdin'/)
  assert.match(session, /getZhiziPersistentSession/)
  assert.match(engine, /GoAgent 直连|queryZhiziSocketGtpAnalysisBatch/)
  assert.match(engine, /session\.runExclusive/)
  assert.match(engine, /channel\.restart/)
  assert.match(engine, /ZHIZI_COLD_START_GTP_TIMEOUT_MS = 60_000/)
  assert.match(engine, /queryZhiziSpawnGtpAnalysisBatch/)
  assert.match(renderer, /智子云远程算力/)
  assert.match(renderer, /默认本机，远程手动启用/)
  assert.match(renderer, /默认本机：自动选择最佳本地引擎/)
  assert.match(renderer, /检测并启用/)
  assert.match(renderer, /回到本地分析/)
  assert.match(renderer, /只检测连接/)
  assert.match(renderer, /testZhiziCloudConnection/)
  assert.match(renderer, /enableZhiziCloudConnection/)
  assert.match(renderer, /高级兼容选项/)
  assert.doesNotMatch(renderer, /iKataGo 远程算力/)
  assert.match(renderer, /智子云未登录：请先在设置里用账号密码或短信验证码登录智子云/)
  assert.match(renderer, /localizeKataGoStatus\(\s*dashboard\.systemProfile\.katagoStatus/)
  assert.match(renderer, /只有你手动启用智子云直连时/)
  assert.match(renderer, /智子云主账号/)
  assert.match(renderer, /VIP 共享引擎/)
  assert.match(renderer, /vip-share/)
  assert.match(renderer, /独享 1x/)
  assert.match(renderer, /按算力和时间计费/)
  assert.match(renderer, /zz- 开头的是连接账号/)
  assert.match(renderer, /登录智子云/)
  assert.match(renderer, /发送验证码/)
  assert.match(renderer, /验证码登录/)
  assert.match(renderer, /loginZhiziCloudPassword/)
  assert.match(renderer, /sendZhiziCloudLoginCode/)
  assert.match(renderer, /loginZhiziCloudCode/)
  assert.match(renderer, /logoutZhiziCloud/)
  assert.match(renderer, /退出智子云登录/)
  assert.match(renderer, /刷新远程会话/)
  assert.match(renderer, /zhiziUsername/)
  assert.match(renderer, /getSavedZhiziToken/)
  assert.match(renderer, /value=\{katagoEngineModeForSettings\}/)
  assert.match(preload, /zhizi:get-saved-token/)
  assert.match(preload, /zhizi:login-password/)
  assert.match(preload, /zhizi:send-code/)
  assert.match(preload, /zhizi:login-code/)
  assert.match(preload, /zhizi:logout/)
  assert.match(preload, /zhizi:test-connection/)
  assert.match(preload, /zhizi:enable/)
  assert.match(main, /hasZhiziToken/)
  assert.match(main, /loginZhiziCloudByPassword/)
  assert.match(main, /sendZhiziCloudLoginCode/)
  assert.match(main, /loginZhiziCloudByCode/)
  assert.match(main, /katagoEngineMode: 'zhizi'/)
  assert.match(main, /ipcMain\.handle\('zhizi:logout'/)
  assert.match(main, /ipcMain\.handle\('zhizi:test-connection'/)
  assert.match(main, /ipcMain\.handle\('zhizi:enable'/)
  assert.match(main, /probeZhiziCloudConnection/)
  assert.match(main, /resetZhiziPersistentSession/)
  assert.match(probe, /getZhiziCloudAccountStatus/)
  assert.match(probe, /queryZhiziGtpAnalysisBatch/)
  assert.match(probe, /visitsPerSecond/)
  assert.match(main, /cancelKataGoAnalysis\(\{\}\)/)
  assert.match(main, /zhiziToken: ''/)
  assert.match(main, /katagoEngineMode: 'auto'/)
  assert.match(main, /zhiziUseWhenLocalSlow: false/)
  assert.match(main, /已退出智子云登录/)
  assert.match(store, /secretStore\.delete\('zhiziToken'\)/)
  assert.match(store, /localAnalysisDefaultApplied: false/)
  assert.match(store, /migrateLocalAnalysisDefault/)
  assert.match(store, /katagoEngineMode === 'zhizi' \|\| settings\.katagoEngineMode === 'ikatago' \? 'auto'/)
  assert.match(i18n, /zhiziCloudLoginRequired/)
  assert.match(i18n, /Zhizi Cloud Login Required/)
  assert.match(i18n, /zhiziCloudDirectReady/)
  assert.match(auth, /https:\/\/www\.zhizigo\.com\/api\/cluster\/account\/login/)
  assert.doesNotMatch(auth, /connectAccount\/login/)
  assert.match(auth, /connectAccount\/fetch/)
  assert.match(auth, /connectUsernameMasked/)
  assert.match(auth, /这是智子云连接账号，不是可直接登录的主账号/)
  assert.match(auth, /https:\/\/www\.zhizigo\.com\/api\/cluster\/account\/send-code/)
  assert.match(auth, /https:\/\/www\.zhizigo\.com\/api\/cluster\/account\/fast-login/)
  assert.match(auth, /type: 'fast_login'/)
  assert.match(auth, /verificationCode/)
  assert.match(auth, /findToken/)
  assert.match(protocol, /--engine-type', 'go'/)
  assert.match(protocol, /--gpu-type', gpuType/)
  assert.match(protocol, /'vip-share'/)
  assert.match(protocol, /--kata-name', 'katago-TENSORRT'/)
  assert.match(protocol, /--kata-weight', '28bnbt'/)
  assert.match(docs, /--gpu-type vip-share/)
  assert.match(docs, /独享 1x \/ 3x \/ 6x/)
  assert.match(docs, /zz-ikatago/)
  assert.match(docs, /Socket\.IO/)
  assert.match(docs, /kata-analyze/)
  assert.match(docs, /后续只需要启动 GoAgent/)
})
